name: CI

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Go
        uses: actions/setup-go@v3
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Lint
        uses: golangci/golangci-lint-action@v3
      -
        name: Run unit-test
        run: go test $(go list ./... | grep -v /integration-test)
      -
        name: Install golang-migrate
        run: |
          curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | sudo bash
          sudo apt-get update
          sudo apt-get install migrate
      -
        name: Create .env file
        run: cp .env.example .env
      -
        name: Make migrations
        run: |
          docker-compose up -d mongodb-service
          migrate -path migrations -database "mongodb://user:password@localhost:27017/recognition?authSource=admin" up
          docker-compose stop mongodb-service
      -
        name: Run integration tests
        run: sudo docker-compose run integration

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: molel/${{ github.event.repository.name }}:latest
